backend:
  name: git-gateway
  branch: master

media_folder:  packages/personal-blog/content/assets
public_folder: packages/personal-blog/public
collections:
  - name: blog
    label: Blog
    folder: packages/personal-blog/content/blog
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}/index.md"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }